services:
  app:
    image: ghcr.io/xlair-dev/dashboard:latest@sha256:4ba9e677db4fea2e18dddea1a354080be729639eaf31e2d48169c899149b3e6b
    container_name: xlair-dashboard
    ports:
      - "${HOST_PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
    restart: unless-stopped
