services:
  app:
    image: ghcr.io/xlair-dev/dashboard:latest@sha256:49ebe35f15b10ac830b790bbc69fd121ab2bb1a8651f0e167544c9f8d243dc90
    container_name: xlair-dashboard
    ports:
      - "${HOST_PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
    restart: unless-stopped
