services:
  app:
    image: ghcr.io/xlair-dev/dashboard:latest@sha256:60611f159eb3a92010ef5f33c153e7251c134283271cb2b0491466d1179b8c29
    container_name: xlair-dashboard
    ports:
      - "${HOST_PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
    restart: unless-stopped
